### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by Matt-Lepley** [wookee55/splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by wookee55** [comment]
Hi Matt,

Just added the following meta tag:
<meta name="viewport" content="width=device-width, initial-scale=1">

Bryan

**Comment by Matt-Lepley** [comment]
Great Job! 

Keep up the good work.

**Comment by wookee55** [comment]
Thanks! :)
